# Generated by Django 3.2.3 on 2021-05-23 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 23, 16, 6, 55, 157885), null=True),
        ),
    ]
