# Generated by Django 3.2.3 on 2021-05-23 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0002_alter_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 23, 16, 7, 31, 386354), null=True),
        ),
    ]
