# Generated by Django 3.2.3 on 2021-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0002_auto_20210520_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hi, my name is <django.db.models.query_utils.DeferredAttribute object at 0x7fe65f5a8310>', max_length=500),
        ),
    ]
