# Generated by Django 3.2.3 on 2021-05-23 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0003_alter_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 23, 17, 2, 8, 599283), null=True),
        ),
    ]
