# Generated by Django 3.2.3 on 2021-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0004_auto_20210521_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hi, my name is Alexa', max_length=500),
        ),
    ]
