# Generated by Django 3.2.3 on 2021-05-22 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['?']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_insta.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 5, 22), null=True),
        ),
    ]
