# Generated by Django 3.2.3 on 2021-05-24 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0005_alter_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 19, 15, 8, 117678), null=True),
        ),
    ]
