# Generated by Django 3.2.3 on 2021-05-24 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0006_alter_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 24, 22, 57, 46, 285147), null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
