# Generated by Django 3.2.3 on 2021-05-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0008_auto_20210525_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follownotification',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='inboxnotification',
            name='inbox',
        ),
        migrations.RemoveField(
            model_name='likenotification',
            name='like',
        ),
        migrations.RemoveField(
            model_name='message',
            name='owner_inbox',
        ),
        migrations.RemoveField(
            model_name='message',
            name='post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reciever_inbox',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='owner',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.DeleteModel(
            name='CommentNotification',
        ),
        migrations.DeleteModel(
            name='FollowNotification',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
        migrations.DeleteModel(
            name='InboxNotification',
        ),
        migrations.DeleteModel(
            name='LikeNotification',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
